# -*- coding: utf-8 -*-
"""vityarthiproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKS2yIOi-dUsUHmthcbMOut1JMU2go9x
"""

import sys
!{sys.executable} -m pip install googletrans==4.0.0-rc1
from googletrans import Translator, LANGUAGES

translator = Translator()
history = []
def basic_translate():
    text = input("\nEnter text to translate: ")
    dest_lang = input("Enter destination language code (e.g., hi, fr, es): ")

    result = translator.translate(text, dest=dest_lang)

    print(f"\nTranslated Text: {result.text}")
    print(f"Detected Source Language: {result.src}")

    history.append((result.src, dest_lang, text, result.text))

def batch_translate():
    n = int(input("\nHow many lines do you want to translate? "))

    texts = []
    for i in range(n):
        t = input(f"Enter line {i+1}: ")
        texts.append(t)

    dest_lang = input("Enter destination language code: ")

    results = translator.translate(texts, dest=dest_lang)

    print("\n--- Batch Translation Output ---")
    for r in results:
        print(f"{r.origin} → {r.text}")
        history.append((r.src, dest_lang, r.origin, r.text))


def file_translate():
    file_path = input("\nEnter .txt file path: ")

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()

        dest_lang = input("Enter destination language code: ")

        result = translator.translate(content, dest=dest_lang)

        output_file = "translated_output.txt"
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(result.text)

        print(f"\nTranslation saved to: {output_file}")

        history.append(("auto", dest_lang, "FILE_CONTENT", result.text))

    except FileNotFoundError:
        print("File not found! Make sure path is correct.")



def show_history():
    if not history:
        print("\nNo translations done yet.")
        return

    print("\n--- Translation History ---")
    for i, h in enumerate(history):
        print(f"{i+1}. [{h[0]} → {h[1]}] {h[2]} → {h[3]}")



def list_languages():
    print("\n--- Supported Languages ---")
    for code, lang in LANGUAGES.items():
        print(f"{code} : {lang}")


def detect_language():
    text = input("\nEnter text to detect language: ")
    result = translator.detect(text)
    print(f"Detected Language: {LANGUAGES[result.lang]} ({result.lang})")



while True:
    print("\n========= TEXT TRANSLATOR TOOL =========")
    print("1. Basic Translation")
    print("2. Batch Translation")
    print("3. File Translation (.txt)")
    print("4. Show Translation History")
    print("5. List Supported Languages")
    print("6. Detect Language")
    print("7. Exit")

    choice = input("\nEnter choice: ")

    if choice == "1":
        basic_translate()
    elif choice == "2":
        batch_translate()
    elif choice == "3":
        file_translate()
    elif choice == "4":
        show_history()
    elif choice == "5":
        list_languages()
    elif choice == "6":
        detect_language()
    elif choice == "7":
        print("Exiting...")
        break
    else:
        print("Invalid choice! Try again.")